name: run web.py

on:
  push:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content

      - name: setup node
        uses: actions/setup-node@v3 # setup node

      - name: install dependencies
        run: npm install

      - name: execute generate.js script
        run: node generate.js

      # commit results to repository
      - name: Commit results
        run: |
          git config --local user.name github-actions
          git config --local user.email github-actions@github.com
          git add _data/*
          git commit -m "Update _data"
          git push